/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gmail_cheesedude54321_utility_HighResolutionTimer */

#ifndef _Included_com_gmail_cheesedude54321_utility_HighResolutionTimer
#define _Included_com_gmail_cheesedude54321_utility_HighResolutionTimer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gmail_cheesedude54321_utility_HighResolutionTimer
 * Method:    timeBeginPeriod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_cheesedude54321_utility_HighResolutionTimer_timeBeginPeriod
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gmail_cheesedude54321_utility_HighResolutionTimer
 * Method:    timeEndPeriod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_cheesedude54321_utility_HighResolutionTimer_timeEndPeriod
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
